title: Chai With Py
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Chai With Py, where we combine our love for chai and coding to bring you the latest and greatest in AI and ML. We're two computer science undergraduates from India, who are on a mission to make AI accessible and fun for everyone. Whether we're experimenting with the latest Python libraries or exploring the depths of NLP, we're always on the lookout for new and exciting ways to push the boundaries of what's possible. So grab a chai, and join us on our journey as we dive into the world of AI and ML, one sip at a time!
  ---
  <b>Supriti Vijay</b><br>I am Supriti Vijay, ML Researcher at Adobe. Completed my undergrad in Computer Science Engineering at the Manipal Institute Of Technology, India. My research interest lies in the field of Natural Language Processing. My past work involves Social Network Science, Interpretability and Text Classification. Happy to chai your acquaintance ;)
  ---
  <b>Aman Priyanshu</b><br>I am Aman Priyanshu, a master's student Carnegie Mellon University. Completed my undergrad at Manipal Institute of Technology, in Information Technology. My research interests include Privacy Preserving Machine Learning, Explainable AI, Fairness, and AI for Social Good. I have recently focused on areas such as Reinforcement Learning, Causal Inference, Bias Mitigation, and Low-Resource Computations. Chai to meet you!
permalink: ':title/'
baseurl: "/one-minute-fair-privacy" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: ChaiWithPy1 #if your site has a twitter account, enter it here

# Author Settings
author: One Minute Fairness and Privacy (Supriti Vijay & Aman Priyanshu) # add your name
author-img: profile.jpg # add your photo
about-author: Welcome to Chai With Py's One Minute Fairness and Privacy, which aims to provide you the current happenings in the world of Fairness, Privacy, and AI. # add description
social-twitter: ChaiWithPy1 # add your Twitter handle
social-facebook:  # add your Facebook handle
social-github: ChaiWithPy # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: supritivijay@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
